# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use
# dvc repro -f
# Individual stage can be executed using:
# dvc repro <stage>

stages:
  list:
    cmd: stages/01_list.sh
    deps:
      - stages/01_list.sh
    outs:
      - list:
          persist: true
  download:
    cmd: stages/02_download.sh
    deps:
      - stages/02_download.sh
      - list
    outs:
      - download:
          persist: true # Allow the stage to avoid downloading unchanged files
  unzip:
    cmd: uv run python3 stages/03_unzip.py
    deps:
      - stages/03_unzip.py
      - download
    outs:
      - raw:
          persist: true
  build:
    cmd: uv run python3 stages/04_build.py
    deps:
      - stages/04_build.py
      - raw
    outs:
      - brick:
          persist: true