# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use
# dvc repro -f
# Individual stage can be executed using:
# dvc repro <stage>

stages:
  list:
    cmd: stages/01_list.sh
    deps:
      - stages/00_config.sh
      - stages/01_list.sh
    outs:
      - list
  download:
    cmd: stages/02_download.sh
    deps:
      - stages/00_config.sh
      - stages/02_download.sh
      - stages/02_download_async.py
      - list
    outs:
      - raw:
          persist: true # Allow the stage to avoid downloading unchanged files
  build:
    cmd: stages/03_build.sh
    deps:
      - stages/00_config.sh
      - stages/03_build.sh
      - stages/build_parquet.py
      - stages/json2parquet.py
      - raw
      - list
    outs:
      - brick
