[project]
name = "openfda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "biobricks>=0.3.9",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "pyarrow>=20.0.0",
    "toolz>=1.0.0",
]
