name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Nix cache
      uses: cachix/cachix-action@v12
      with:
        name: devenv
        
    - name: Run tests
      run: |
        nix develop --command python3 -m pytest test/ -v --tb=short
        
    - name: Run tests with coverage
      run: |
        nix develop --command python3 -m pytest test/ --cov=stages --cov-report=xml --cov-report=term-missing
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 